version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: ticket-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg1234
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
